#=================================================
# Description: Batch Trigger Build
# Lisence: MIT
# Author: helmiau
# Blog: https://helmiau.com
#=================================================

name: Batch Trigger Build

on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 18 * * *
#  watch:
#    types: started

env:
  REPO_OWNER: helmiau
  REPO_NAME: HelmiWrt-OS
  BRANCH_NAME: main
  # wait_interval
  DELAY_INT: 300
  # wait_workflow
  WAIT_WF: true
  # trigger_workflow
  TRIGGER_WF: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Running NanoPi R2S Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-nanopi-r2s.yml
          ref: ${{ env.BRANCH_NAME }}
          # wait_interval: ${{ env.DELAY_INT }}
          # trigger_workflow: ${{ env.TRIGGER_WF }}
          # wait_workflow: ${{ env.WAIT_WF }}

      - name: Processing Delay Time
        run: |
          sleep $DELAY_INT
          echo "Running NanoPi R2S Build done"

      - name: Running NanoPi R4S Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-nanopi-r4s.yml
          ref: ${{ env.BRANCH_NAME }}
          # wait_interval: ${{ env.DELAY_INT }}
          # trigger_workflow: ${{ env.TRIGGER_WF }}
          #wait_workflow: ${{ env.WAIT_WF }}

      - name: Processing Delay Time
        run: |
          sleep $DELAY_INT
          echo "Running NanoPi R4S Build done"

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 3
